name: base
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - conda=22.11.1
  - conda-content-trust=0.1.3
  - conda-package-handling=1.9.0
  - cryptography=38.0.1
  - idna=3.4
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - pluggy=1.0.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.8
  - readline=8.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - toolz=0.12.0
  - urllib3=1.26.13
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.28.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - chardet==5.2.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - dask==2022.5.0
      - dataproperty==1.1.0
      - datasets==2.16.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - evaluate==0.4.3
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fastapi==0.115.12
      - fastjsonschema==2.19.1
      - ffmpy==0.5.0
      - filelock==3.14.0
      - fonttools==4.53.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2023.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gradio==5.23.1
      - gradio-client==1.8.0
      - groovy==0.1.2
      - grpcio==1.64.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.29.3
      - importlib-resources==6.5.2
      - ipykernel==6.29.4
      - ipython==8.25.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.2
      - jupyterlab-language-pack-zh-cn==4.2.post1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - locket==1.0.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.7
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.2.0
      - multiprocess==0.70.15
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - nltk==3.9.1
      - notebook-shim==0.2.4
      - numexpr==2.10.2
      - numpy==1.26.3
      - omegaconf==2.3.0
      - orjson==3.10.16
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - pathvalidate==3.2.3
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - portalocker==3.1.1
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - propcache==0.3.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==19.0.1
      - pyarrow-hotfix==0.6
      - pycountry==24.6.1
      - pydantic==2.11.0
      - pydantic-core==2.33.0
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - python-multipart==0.0.20
      - pytz==2025.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rouge-score==0.1.2
      - rpds-py==0.18.1
      - ruff==0.11.2
      - sacrebleu==1.5.0
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.1.99
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlitedict==2.1.0
      - stack-data==0.6.3
      - starlette==0.46.1
      - supervisor==4.2.5
      - sympy==1.12.1
      - tabledata==1.3.4
      - tcolorpy==0.1.7
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.3.0
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tomlkit==0.13.2
      - torch==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - tornado==6.4.1
      - tqdm==4.65.0
      - traitlets==5.14.3
      - transformers==4.35.2
      - triton==2.1.0
      - typepy==1.3.4
      - typer==0.15.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2025.1
      - uri-template==1.3.0
      - uvicorn==0.34.0
      - wandb==0.19.8
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: /root/miniconda3
